Pin nightly due to ICE
Triggered by packed_simd, a dependency of encoding_rs:

error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:37:32: could not fully normalize `<A as sealed::SimdArray>::Tuple`